//! Build script that embeds the canonical companion skill tree into the
//! binary so a downloaded `adr` binary is self-contained.
//!
//! It walks the canonical `skills/documentation/adr-creator` directory
//! (relative to the workspace, never a copy committed inside this crate) and
//! generates `$OUT_DIR/embedded_skill.rs`, a table of
//! `(relative-path, &'static [u8])` entries backed by `include_bytes!`. The
//! bytes are baked in at compile time, so no repository is needed at runtime.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    // The canonical, single-source-of-truth skill lives two levels up under
    // `skills/`. We embed from there rather than duplicating the tree.
    let skill_root = manifest_dir
        .join("../../skills/documentation/adr-creator")
        .canonicalize()
        .expect("canonical skill directory must exist at build time");

    let skill_name = skill_root
        .file_name()
        .and_then(|n| n.to_str())
        .expect("skill directory has a name")
        .to_string();

    let mut files: BTreeMap<String, PathBuf> = BTreeMap::new();
    collect_files(&skill_root, &skill_root, &mut files);

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs; do not edit.\n");
    generated.push_str(&format!(
        "pub static EMBEDDED_SKILL_NAME: &str = {skill_name:?};\n\n"
    ));
    generated.push_str("pub static EMBEDDED_SKILL_FILES: &[(&str, &[u8])] = &[\n");
    for (rel, abs) in &files {
        let abs_str = abs.to_str().expect("path is valid UTF-8");
        generated.push_str(&format!("    ({rel:?}, include_bytes!({abs_str:?})),\n"));
        // Rebuild when any embedded file changes.
        println!("cargo:rerun-if-changed={abs_str}");
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("embedded_skill.rs"), generated)
        .expect("write generated embedded_skill.rs");

    // Rebuild when files are added to or removed from the tree.
    println!("cargo:rerun-if-changed={}", skill_root.display());
}

/// Recursively collect every regular file under `dir`, keyed by its
/// forward-slash path relative to `root`.
fn collect_files(root: &Path, dir: &Path, out: &mut BTreeMap<String, PathBuf>) {
    let entries = fs::read_dir(dir).expect("read skill directory");
    for entry in entries {
        let entry = entry.expect("read skill directory entry");
        let path = entry.path();
        let file_type = entry.file_type().expect("stat skill entry");
        if file_type.is_dir() {
            collect_files(root, &path, out);
        } else if file_type.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("entry is under root")
                .to_str()
                .expect("relative path is valid UTF-8")
                .replace('\\', "/");
            out.insert(rel, path);
        }
    }
}
