//! The generated ADR catalogue.
//!
//! `index.md` is derived entirely from the records' frontmatter, so it is safe
//! to overwrite and pointless to hand-edit. It exists for humans browsing the
//! directory; machines should read the records themselves through `adr list
//! --json`, which cannot be stale by construction.

use std::fs;
use std::path::{Path, PathBuf};

use common::{Error, Result};
use serde::Serialize;

use crate::record::{Record, Status};

/// The generated catalogue's file name within the ADR directory.
pub const FILE_NAME: &str = "index.md";

/// One record as machine-readable JSON, for `adr list --json`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Row {
    /// The record's identity.
    pub slug: String,
    /// The decision title.
    pub title: String,
    /// The kind of change the decision accompanies.
    pub branch_type: &'static str,
    /// Where the decision sits in its lifecycle.
    pub status: &'static str,
    /// The creation date.
    pub date: String,
    /// Who wrote it.
    pub author: String,
    /// Filtering tags.
    pub tags: Vec<String>,
    /// The slug that replaced this decision, when one did.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub superseded_by: Option<String>,
}

/// Project `records` into serialisable rows, preserving their order.
pub fn rows(records: &[Record]) -> Vec<Row> {
    records
        .iter()
        .map(|r| Row {
            slug: r.slug.clone(),
            title: r.meta.title.clone(),
            branch_type: r.meta.branch_type.as_str(),
            status: r.meta.status.as_str(),
            date: r.meta.date.clone(),
            author: r.meta.author.clone(),
            tags: r.meta.tags.clone(),
            superseded_by: r.meta.superseded_by.clone(),
        })
        .collect()
}

/// Render the catalogue for `records`, grouped by status in lifecycle order.
///
/// A generated-file banner leads the document so nobody edits it by hand and
/// loses the change on the next run.
pub fn render(records: &[Record], today: &str) -> String {
    let mut out = String::from("# Architecture Decision Records\n\n");
    out.push_str(&format!(
        "<!-- Generated by `adr index` on {today}. Do not edit; change the records' frontmatter instead. -->\n\n"
    ));

    if records.is_empty() {
        out.push_str("No decisions recorded yet. Create one with `adr create`.\n");
        return out;
    }

    out.push_str(&format!(
        "{} decision{} recorded.\n",
        records.len(),
        if records.len() == 1 { "" } else { "s" }
    ));

    for status in Status::ALL {
        let group: Vec<&Record> = records
            .iter()
            .filter(|r| r.meta.status == status)
            .collect();
        if group.is_empty() {
            continue;
        }
        out.push_str(&format!("\n## {}\n\n", heading_for(status)));
        out.push_str("| Decision | Type | Date | Notes |\n");
        out.push_str("| --- | --- | --- | --- |\n");
        for r in group {
            out.push_str(&format!(
                "| [{}]({}) | {} | {} | {} |\n",
                escape_cell(&r.meta.title),
                r.file_name(),
                r.meta.branch_type,
                r.meta.date,
                escape_cell(&notes_for(r)),
            ));
        }
    }
    out
}

/// The section heading for a status group.
fn heading_for(status: Status) -> &'static str {
    match status {
        Status::Proposed => "Proposed",
        Status::ReviewRequested => "Awaiting review",
        Status::Accepted => "In force",
        Status::Deprecated => "Deprecated",
        Status::Superseded => "Superseded",
    }
}

/// The Notes cell: the supersede link when there is one, else the tags.
fn notes_for(r: &Record) -> String {
    if let Some(next) = &r.meta.superseded_by {
        return format!("superseded by `{next}`");
    }
    if let Some(prev) = &r.meta.supersedes {
        return format!("supersedes `{prev}`");
    }
    r.meta
        .tags
        .iter()
        .map(|t| format!("`{t}`"))
        .collect::<Vec<_>>()
        .join(" ")
}

/// Escape the characters that would break out of a markdown table cell.
fn escape_cell(text: &str) -> String {
    text.replace('|', "\\|").replace('\n', " ")
}

/// Write the catalogue for `records` into `dir`, returning its path.
pub fn write(dir: &Path, records: &[Record], today: &str) -> Result<PathBuf> {
    let path = dir.join(FILE_NAME);
    fs::write(&path, render(records, today)).map_err(|e| Error::io(&path, e))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::record::{BranchType, Record};
    use tempfile::TempDir;

    fn record(slug: &str, title: &str, t: BranchType) -> Record {
        Record::new(slug, title, t, "Test User", "2026-09-15", None)
    }

    #[test]
    fn an_empty_collection_says_so() {
        let out = render(&[], "2026-09-15");
        assert!(out.contains("No decisions recorded yet"), "{out}");
        assert!(out.contains("adr create"), "{out}");
    }

    #[test]
    fn the_catalogue_warns_that_it_is_generated() {
        let out = render(&[record("a", "A", BranchType::Feat)], "2026-09-15");
        assert!(out.contains("Generated by `adr index`"), "{out}");
        assert!(out.contains("Do not edit"), "{out}");
    }

    #[test]
    fn records_group_under_their_status_heading() {
        let mut accepted = record("otel", "Adopt OpenTelemetry", BranchType::Feat);
        accepted.transition(Status::Accepted, "2026-09-15T10:00:00Z");
        let proposed = record("tempo", "Adopt Tempo", BranchType::Feat);

        let out = render(&[accepted, proposed], "2026-09-15");
        let in_force = out.find("## In force").expect("in force section");
        let pending = out.find("## Proposed").expect("proposed section");

        assert!(pending < in_force, "lifecycle order puts Proposed first");
        assert!(out.contains("[Adopt OpenTelemetry](otel.md)"), "{out}");
        assert!(out.contains("[Adopt Tempo](tempo.md)"), "{out}");
    }

    #[test]
    fn empty_status_groups_are_omitted() {
        let out = render(&[record("a", "A", BranchType::Feat)], "2026-09-15");
        assert!(!out.contains("## Deprecated"), "{out}");
        assert!(!out.contains("## Superseded"), "{out}");
    }

    #[test]
    fn a_supersede_link_appears_in_the_notes_column() {
        let mut old = record("otel", "Adopt OpenTelemetry", BranchType::Feat);
        old.meta.superseded_by = Some("tempo".to_string());
        old.transition(Status::Superseded, "2026-09-15T10:00:00Z");

        let out = render(&[old], "2026-09-15");
        assert!(out.contains("superseded by `tempo`"), "{out}");
    }

    #[test]
    fn tags_fill_the_notes_column_when_there_is_no_link() {
        let mut r = record("otel", "Adopt OpenTelemetry", BranchType::Feat);
        r.meta.tags = vec!["tracing".into(), "observability".into()];
        let out = render(&[r], "2026-09-15");
        assert!(out.contains("`tracing` `observability`"), "{out}");
    }

    #[test]
    fn a_pipe_in_a_title_cannot_break_the_table() {
        let r = record("odd", "Adopt A | B", BranchType::Feat);
        let out = render(&[r], "2026-09-15");
        assert!(out.contains("Adopt A \\| B"), "{out}");
    }

    #[test]
    fn singular_and_plural_counts_read_correctly() {
        let one = render(&[record("a", "A", BranchType::Feat)], "2026-09-15");
        assert!(one.contains("1 decision recorded"), "{one}");

        let two = render(
            &[
                record("a", "A", BranchType::Feat),
                record("b", "B", BranchType::Fix),
            ],
            "2026-09-15",
        );
        assert!(two.contains("2 decisions recorded"), "{two}");
    }

    #[test]
    fn write_puts_the_catalogue_in_the_directory() {
        let tmp = TempDir::new().unwrap();
        let path = write(tmp.path(), &[record("a", "A", BranchType::Feat)], "2026-09-15").unwrap();

        assert_eq!(path, tmp.path().join("index.md"));
        assert!(fs::read_to_string(&path).unwrap().contains("## Proposed"));
    }

    #[test]
    fn rows_project_every_queryable_field() {
        let mut r = record("otel", "Adopt OpenTelemetry", BranchType::Feat);
        r.meta.tags = vec!["tracing".into()];
        r.meta.superseded_by = Some("tempo".into());

        let rows = rows(&[r]);
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].slug, "otel");
        assert_eq!(rows[0].branch_type, "feat");
        assert_eq!(rows[0].status, "proposed");
        assert_eq!(rows[0].tags, vec!["tracing".to_string()]);
        assert_eq!(rows[0].superseded_by.as_deref(), Some("tempo"));
    }
}
