//! Wiring the ADR hook commands into whichever agent harnesses a project uses.
//!
//! `sync` is idempotent and additive. It reads each harness's own config,
//! inserts only the entries that are missing, and writes the rest back
//! untouched: an unrecognised key in `.claude/settings.json` survives a sync,
//! and running sync twice changes nothing the second time.
//!
//! A project with no harness config is not an error. There is simply nothing to
//! wire, which is what a fresh checkout looks like.

use std::fs;
use std::path::{Path, PathBuf};

use common::{Error, Result};
use serde_json::{json, Map, Value};

/// The binary the hooks invoke.
const BIN: &str = "pantheon-adr";

/// The OpenCode plugin's banner, used to spot a plugin we already wrote.
const PLUGIN_MARKER: &str = "auto-generated by `pantheon-adr sync`";

/// What happened to one harness's configuration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Outcome {
    /// The config was missing entries and has been patched.
    Synced,
    /// Every entry was already present.
    AlreadySynced,
    /// The harness is not used by this project.
    NotDetected,
}

/// The result of syncing one harness.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SyncResult {
    /// The harness's name, as shown in output.
    pub name: &'static str,
    /// What happened.
    pub outcome: Outcome,
    /// The file that was inspected or written.
    pub path: PathBuf,
}

/// The harness lifecycle events wired to ADR commands.
///
/// `matcher` is Claude Code's tool filter; an empty matcher means every tool.
const CLAUDE_HOOKS: [(&str, &str, &str); 3] = [
    ("SessionStart", "", "session-start"),
    ("PostToolUse", "Bash", "post-tool-use"),
    ("Stop", "", "session-end"),
];

/// Sync every supported harness found under `root`.
pub fn sync_all(root: &Path) -> Result<Vec<SyncResult>> {
    Ok(vec![sync_claude(root)?, sync_opencode(root)?])
}

/// Wire the ADR hooks into `.claude/settings.json`.
pub fn sync_claude(root: &Path) -> Result<SyncResult> {
    let dir = root.join(".claude");
    let path = dir.join("settings.json");
    if !dir.is_dir() {
        return Ok(SyncResult {
            name: "claude-code",
            outcome: Outcome::NotDetected,
            path,
        });
    }

    let mut settings = read_json_object(&path)?;
    let mut hooks = settings
        .remove("hooks")
        .and_then(|v| match v {
            Value::Object(map) => Some(map),
            _ => None,
        })
        .unwrap_or_default();

    let mut changed = false;
    for (event, matcher, subcommand) in CLAUDE_HOOKS {
        let command = format!("{BIN} {subcommand}");
        let entries = hooks.entry(event.to_string()).or_insert_with(|| json!([]));
        let Value::Array(list) = entries else {
            // A harness that stores something else under this event is not ours
            // to reshape; leave it and report the file as already handled.
            continue;
        };
        if list.iter().any(|e| mentions_command(e, &command)) {
            continue;
        }
        list.push(json!({
            "matcher": matcher,
            "hooks": [{ "type": "command", "command": command }],
        }));
        changed = true;
    }

    settings.insert("hooks".to_string(), Value::Object(hooks));
    if changed {
        write_json_object(&path, &settings)?;
    }
    Ok(SyncResult {
        name: "claude-code",
        outcome: if changed {
            Outcome::Synced
        } else {
            Outcome::AlreadySynced
        },
        path,
    })
}

/// Whether a hook entry already invokes `command`.
///
/// Matches a path-prefixed variant too, so a project pointing at
/// `./target/debug/pantheon-adr session-start` is not given a duplicate.
fn mentions_command(entry: &Value, command: &str) -> bool {
    entry
        .get("hooks")
        .and_then(|h| h.as_array())
        .into_iter()
        .flatten()
        .filter_map(|h| h.get("command").and_then(|c| c.as_str()))
        .any(|existing| command_matches(existing, command))
}

/// Whether `existing` is `target`, possibly with a path in front of the binary.
fn command_matches(existing: &str, target: &str) -> bool {
    if existing == target {
        return true;
    }
    let Some((bin, args)) = target.split_once(' ') else {
        return false;
    };
    let Some((existing_bin, existing_args)) = existing.split_once(' ') else {
        return false;
    };
    existing_args == args
        && Path::new(existing_bin).file_name().and_then(|n| n.to_str()) == Some(bin)
}

/// The OpenCode plugin that forwards lifecycle events to the ADR commands.
///
/// The `$` is OpenCode's own shell tag, destructured from the plugin context,
/// and `.nothrow()` keeps a missing binary from failing the session.
fn plugin_source() -> String {
    format!(
        "// ADR plugin, {PLUGIN_MARKER}. Do not edit by hand; re-run the command to update.\n\
         export const adr = async ({{ $ }}) => ({{\n\
         \x20 event: async ({{ event }}) => {{\n\
         \x20   if (event.type === \"session.start\") await $`{BIN} session-start`.nothrow();\n\
         \x20   if (event.type === \"session.idle\") await $`{BIN} session-end`.nothrow();\n\
         \x20 }},\n\
         }});\n"
    )
}

/// Write the OpenCode plugin when the project uses OpenCode.
pub fn sync_opencode(root: &Path) -> Result<SyncResult> {
    let detected = ["opencode.json", ".opencode"]
        .iter()
        .any(|name| root.join(name).exists());
    let path = root.join(".opencode").join("plugins").join("adr.js");
    if !detected {
        return Ok(SyncResult {
            name: "opencode",
            outcome: Outcome::NotDetected,
            path,
        });
    }

    if let Ok(existing) = fs::read_to_string(&path) {
        if existing.contains(PLUGIN_MARKER) {
            return Ok(SyncResult {
                name: "opencode",
                outcome: Outcome::AlreadySynced,
                path,
            });
        }
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| Error::io(parent, e))?;
    }
    fs::write(&path, plugin_source()).map_err(|e| Error::io(&path, e))?;
    Ok(SyncResult {
        name: "opencode",
        outcome: Outcome::Synced,
        path,
    })
}

/// Read a JSON object, treating an absent or empty file as `{}`.
fn read_json_object(path: &Path) -> Result<Map<String, Value>> {
    let Ok(text) = fs::read_to_string(path) else {
        return Ok(Map::new());
    };
    if text.trim().is_empty() {
        return Ok(Map::new());
    }
    match serde_json::from_str(&text) {
        Ok(Value::Object(map)) => Ok(map),
        Ok(_) => Err(Error::Config(format!(
            "{}: expected a JSON object at the top level",
            path.display()
        ))),
        Err(e) => Err(Error::Config(format!("{}: {e}", path.display()))),
    }
}

/// Write a JSON object back, pretty-printed and newline-terminated.
fn write_json_object(path: &Path, map: &Map<String, Value>) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| Error::io(parent, e))?;
    }
    let text = serde_json::to_string_pretty(&Value::Object(map.clone()))
        .map_err(|e| Error::json(path.display().to_string(), e))?;
    fs::write(path, format!("{text}\n")).map_err(|e| Error::io(path, e))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[track_caller]
    fn settings(root: &Path) -> Value {
        let path = root.join(".claude").join("settings.json");
        let text = fs::read_to_string(&path).expect("settings.json should exist after a sync");
        serde_json::from_str(&text).expect("settings.json should be valid JSON")
    }

    #[test]
    fn a_project_with_no_harness_is_not_an_error() {
        let tmp = TempDir::new().unwrap();
        let results = sync_all(tmp.path()).unwrap();
        assert!(results.iter().all(|r| r.outcome == Outcome::NotDetected));
    }

    #[test]
    fn claude_hooks_are_added_to_an_empty_settings_file() {
        let tmp = TempDir::new().unwrap();
        fs::create_dir_all(tmp.path().join(".claude")).unwrap();

        let result = sync_claude(tmp.path()).unwrap();
        assert_eq!(result.outcome, Outcome::Synced);

        let hooks = settings(tmp.path());
        for event in ["SessionStart", "PostToolUse", "Stop"] {
            assert!(hooks["hooks"][event].is_array(), "missing {event}");
        }
        assert_eq!(
            hooks["hooks"]["PostToolUse"][0]["matcher"],
            json!("Bash"),
            "PostToolUse is scoped to Bash"
        );
    }

    #[test]
    fn syncing_claude_twice_changes_nothing() {
        let tmp = TempDir::new().unwrap();
        fs::create_dir_all(tmp.path().join(".claude")).unwrap();

        assert_eq!(sync_claude(tmp.path()).unwrap().outcome, Outcome::Synced);
        let first = settings(tmp.path());

        assert_eq!(
            sync_claude(tmp.path()).unwrap().outcome,
            Outcome::AlreadySynced
        );
        assert_eq!(settings(tmp.path()), first);
    }

    #[test]
    fn unrelated_settings_survive_a_sync() {
        let tmp = TempDir::new().unwrap();
        let dir = tmp.path().join(".claude");
        fs::create_dir_all(&dir).unwrap();
        fs::write(
            dir.join("settings.json"),
            r#"{"model":"opus","permissions":{"allow":["Bash(ls)"]}}"#,
        )
        .unwrap();

        sync_claude(tmp.path()).unwrap();
        let out = settings(tmp.path());
        assert_eq!(out["model"], json!("opus"));
        assert_eq!(out["permissions"]["allow"][0], json!("Bash(ls)"));
    }

    #[test]
    fn an_existing_hook_for_another_tool_is_preserved() {
        let tmp = TempDir::new().unwrap();
        let dir = tmp.path().join(".claude");
        fs::create_dir_all(&dir).unwrap();
        fs::write(
            dir.join("settings.json"),
            r#"{"hooks":{"SessionStart":[{"matcher":"","hooks":[{"type":"command","command":"other-tool go"}]}]}}"#,
        )
        .unwrap();

        sync_claude(tmp.path()).unwrap();
        let list = settings(tmp.path())["hooks"]["SessionStart"]
            .as_array()
            .unwrap()
            .clone();
        assert_eq!(list.len(), 2, "ours is appended, theirs is kept");
        assert_eq!(list[0]["hooks"][0]["command"], json!("other-tool go"));
    }

    #[test]
    fn a_path_prefixed_command_counts_as_already_wired() {
        let tmp = TempDir::new().unwrap();
        let dir = tmp.path().join(".claude");
        fs::create_dir_all(&dir).unwrap();
        fs::write(
            dir.join("settings.json"),
            r#"{"hooks":{"SessionStart":[{"matcher":"","hooks":[{"type":"command","command":"./target/debug/pantheon-adr session-start"}]}]}}"#,
        )
        .unwrap();

        sync_claude(tmp.path()).unwrap();
        let list = settings(tmp.path())["hooks"]["SessionStart"]
            .as_array()
            .unwrap()
            .clone();
        assert_eq!(list.len(), 1, "no duplicate for a path-prefixed variant");
    }

    #[test]
    fn command_matching_accepts_a_path_and_rejects_a_different_subcommand() {
        assert!(command_matches(
            "pantheon-adr session-start",
            "pantheon-adr session-start"
        ));
        assert!(command_matches(
            "/usr/local/bin/pantheon-adr session-start",
            "pantheon-adr session-start"
        ));
        assert!(!command_matches(
            "pantheon-adr session-end",
            "pantheon-adr session-start"
        ));
        assert!(!command_matches(
            "other session-start",
            "pantheon-adr session-start"
        ));
    }

    #[test]
    fn malformed_settings_are_reported_not_overwritten() {
        let tmp = TempDir::new().unwrap();
        let dir = tmp.path().join(".claude");
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("settings.json"), "{not json").unwrap();

        assert!(sync_claude(tmp.path()).is_err());
        assert_eq!(
            fs::read_to_string(dir.join("settings.json")).unwrap(),
            "{not json"
        );
    }

    #[test]
    fn a_non_object_settings_file_is_refused() {
        let tmp = TempDir::new().unwrap();
        let dir = tmp.path().join(".claude");
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("settings.json"), "[1, 2, 3]").unwrap();

        let err = sync_claude(tmp.path()).unwrap_err().to_string();
        assert!(err.contains("JSON object"), "{err}");
    }

    #[test]
    fn opencode_is_detected_by_either_marker() {
        for marker in ["opencode.json", ".opencode"] {
            let tmp = TempDir::new().unwrap();
            if marker.ends_with(".json") {
                fs::write(tmp.path().join(marker), "{}").unwrap();
            } else {
                fs::create_dir_all(tmp.path().join(marker)).unwrap();
            }
            assert_eq!(
                sync_opencode(tmp.path()).unwrap().outcome,
                Outcome::Synced,
                "{marker} should be detected"
            );
        }
    }

    #[test]
    fn the_opencode_plugin_is_written_once() {
        let tmp = TempDir::new().unwrap();
        fs::write(tmp.path().join("opencode.json"), "{}").unwrap();

        let first = sync_opencode(tmp.path()).unwrap();
        assert_eq!(first.outcome, Outcome::Synced);
        let source = fs::read_to_string(&first.path).expect("plugin should be written");
        assert!(source.contains("Do not edit by hand"), "{source}");
        assert!(
            source.contains("await $`pantheon-adr session-start`.nothrow()"),
            "the plugin must keep OpenCode's shell tag: {source}"
        );
        assert!(
            source.contains("await $`pantheon-adr session-end`.nothrow()"),
            "{source}"
        );
        assert!(source.contains("export const adr"), "{source}");

        assert_eq!(
            sync_opencode(tmp.path()).unwrap().outcome,
            Outcome::AlreadySynced
        );
    }

    #[test]
    fn a_foreign_plugin_at_that_path_is_replaced_only_once_marked() {
        let tmp = TempDir::new().unwrap();
        fs::write(tmp.path().join("opencode.json"), "{}").unwrap();
        let path = tmp.path().join(".opencode").join("plugins").join("adr.js");
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, "// hand written\n").unwrap();

        assert_eq!(sync_opencode(tmp.path()).unwrap().outcome, Outcome::Synced);
        assert!(fs::read_to_string(&path).unwrap().contains(PLUGIN_MARKER));
    }
}
