#!/bin/bash
# full-debug-session.sh - Complete debugging session from start to finish
#
# Usage: ./full-debug-session.sh <baseline-branch> <changed-branch> <app-url> <build-command> <start-command>
#
# Example:
#   ./full-debug-session.sh main fix/code-annotations "http://localhost:19888" "bun run build:hook" "bun run apps/hook/server/index.ts plan"

set -e

BASELINE_BRANCH="${1:-main}"
CHANGED_BRANCH="${2:-HEAD}"
APP_URL="${3:-http://localhost:3000}"
BUILD_CMD="${4:-npm run build}"
START_CMD="${5:-npm start}"

TIMESTAMP=$(date '+%Y-%m-%d-%H%M%S')
REPORT_DIR="./docs/change-fix/$TIMESTAMP"
BASELINE_DIR="$REPORT_DIR/baseline"
CHANGED_DIR="$REPORT_DIR/changed"

echo "========================================="
echo "   UI Debug Workflow - Full Session"
echo "========================================="
echo ""
echo "Configuration:"
echo "  Baseline Branch: $BASELINE_BRANCH"
echo "  Changed Branch:  $CHANGED_BRANCH"
echo "  Application URL: $APP_URL"
echo "  Build Command:   $BUILD_CMD"
echo "  Start Command:   $START_CMD"
echo "  Report Directory: $REPORT_DIR"
echo ""

mkdir -p "$BASELINE_DIR" "$CHANGED_DIR"

# Save configuration
cat > "$REPORT_DIR/config.json" << EOF
{
  "timestamp": "$TIMESTAMP",
  "baselineBranch": "$BASELINE_BRANCH",
  "changedBranch": "$CHANGED_BRANCH",
  "appUrl": "$APP_URL",
  "buildCommand": "$BUILD_CMD",
  "startCommand": "$START_CMD"
}
EOF

echo "========================================="
echo "PHASE 1: Baseline Evidence Collection"
echo "========================================="
echo ""

# Checkout baseline
echo "→ Checking out baseline branch: $BASELINE_BRANCH"
git checkout "$BASELINE_BRANCH"
git log -1 --oneline > "$BASELINE_DIR/commit-info.txt"

# Build baseline
echo "→ Building baseline..."
$BUILD_CMD > "$BASELINE_DIR/build-output.log" 2>&1
echo "✅ Build complete"

# Start server in background
echo "→ Starting server..."
$START_CMD > "$BASELINE_DIR/server-output.log" 2>&1 &
SERVER_PID=$!
echo "$SERVER_PID" > "$REPORT_DIR/server-baseline.pid"
sleep 5

# Capture baseline evidence
echo "→ Capturing baseline evidence..."
./scripts/capture-evidence.sh "baseline-session" "$APP_URL" "$BASELINE_DIR"

# Stop server
echo "→ Stopping server (PID: $SERVER_PID)..."
kill $SERVER_PID 2>/dev/null || true
wait $SERVER_PID 2>/dev/null || true
sleep 2

echo "✅ Baseline evidence collected"
echo ""

echo "========================================="
echo "PHASE 2: Changed Evidence Collection"
echo "========================================="
echo ""

# Checkout changed branch
echo "→ Checking out changed branch: $CHANGED_BRANCH"
git checkout "$CHANGED_BRANCH"
git log -1 --oneline > "$CHANGED_DIR/commit-info.txt"

# Save git diff
echo "→ Capturing git diff..."
git diff "$BASELINE_BRANCH...$CHANGED_BRANCH" > "$CHANGED_DIR/git-diff.patch"

# Build changed version
echo "→ Building changed version..."
$BUILD_CMD > "$CHANGED_DIR/build-output.log" 2>&1
echo "✅ Build complete"

# Start server in background
echo "→ Starting server..."
$START_CMD > "$CHANGED_DIR/server-output.log" 2>&1 &
SERVER_PID=$!
echo "$SERVER_PID" > "$REPORT_DIR/server-changed.pid"
sleep 5

# Capture changed evidence
echo "→ Capturing changed evidence..."
./scripts/capture-evidence.sh "changed-session" "$APP_URL" "$CHANGED_DIR"

# Stop server
echo "→ Stopping server (PID: $SERVER_PID)..."
kill $SERVER_PID 2>/dev/null || true
wait $SERVER_PID 2>/dev/null || true
sleep 2

echo "✅ Changed evidence collected"
echo ""

echo "========================================="
echo "PHASE 3: Comparison & Report Generation"
echo "========================================="
echo ""

# Compare evidence
echo "→ Comparing evidence..."
./scripts/compare-evidence.sh "$BASELINE_DIR" "$CHANGED_DIR" "$REPORT_DIR/comparison.md"

# Generate comprehensive report template
echo "→ Generating report template..."
cat > "$REPORT_DIR/REPORT.md" << 'EOF'
# Debug Report

**Date**: $(date '+%Y-%m-%d %H:%M:%S')
**Generated by**: ui-debug-workflow skill

---

## Summary

- **Issue**: [Describe the issue being tested]
- **Status**: ⬜ Fixed | ⬜ Partially Fixed | ⬜ Not Fixed | ⬜ Regression

## Test Configuration

```json
EOF

cat "$REPORT_DIR/config.json" >> "$REPORT_DIR/REPORT.md"

cat >> "$REPORT_DIR/REPORT.md" << 'EOF'
```

## Branches

### Baseline

```
EOF

cat "$BASELINE_DIR/commit-info.txt" >> "$REPORT_DIR/REPORT.md"

cat >> "$REPORT_DIR/REPORT.md" << 'EOF'
```

### Changed

```
EOF

cat "$CHANGED_DIR/commit-info.txt" >> "$REPORT_DIR/REPORT.md"

cat >> "$REPORT_DIR/REPORT.md" << 'EOF'
```

## Changes Made

See [git-diff.patch](./changed/git-diff.patch) for complete diff.

## Evidence

### Baseline
- [Screenshots](./baseline/)
- [Build Log](./baseline/build-output.log)
- [Server Log](./baseline/server-output.log)

### Changed
- [Screenshots](./changed/)
- [Build Log](./changed/build-output.log)
- [Server Log](./changed/server-output.log)

## Comparison

See [comparison.md](./comparison.md) for detailed comparison.

## Test Results

- [ ] **TC-01**: [Test case description]
- [ ] **TC-02**: [Test case description]
- [ ] **TC-03**: [Test case description]

## Findings

### Issues Fixed

1. [Issue 1]
2. [Issue 2]

### Regressions Introduced

1. [Regression 1] (if any)

### Outstanding Issues

1. [Outstanding 1] (if any)

## Recommendations

1. [Recommendation 1]
2. [Recommendation 2]

## Next Steps

- [ ] [Action item 1]
- [ ] [Action item 2]

---

**TODO**: Fill out this template with actual findings and analysis.
EOF

echo "✅ Report template generated"
echo ""

echo "========================================="
echo "   Debug Session Complete"
echo "========================================="
echo ""
echo "📁 Report Location: $REPORT_DIR"
echo ""
echo "Generated files:"
ls -lh "$REPORT_DIR" | tail -n +2 | awk '{print "  - " $9}'
echo ""
echo "Next steps:"
echo "  1. Review screenshots in baseline/ and changed/"
echo "  2. Read comparison.md for automated analysis"
echo "  3. Fill out REPORT.md with your findings"
echo "  4. Share the report with stakeholders"
echo ""
