#!/usr/bin/env bash
#
# check-no-cache-files.sh
#
# Guardrail: fail if a cache or dependency folder is about to be committed.
# These folders are generated by running a tool (terragrunt, terraform, python,
# node), not authored, and they bloat the repository: a single committed
# .terragrunt-cache once added 540 files and a local path.
#
# Matches whole folder names, so a lock file such as .terraform.lock.hcl, or a
# document called terragrunt-cache-notes.md, is fine. Test fixtures under
# crates/*/tests/golden-corpus/ are exempt. Paths that no longer exist on disk
# (a deletion being committed) are ignored, so removing cache files is allowed.
#
# Usage:
#   scripts/check-no-cache-files.sh [--root DIR] <path>...   the staged files (pre-commit hook)
#   scripts/check-no-cache-files.sh [--root DIR] --tracked   every file git tracks (for CI)
#
# Exit: 0 = clean; 1 = cache folder(s) found.
set -uo pipefail

root=""
tracked=0
paths=()

while [ $# -gt 0 ]; do
  case "$1" in
    --root) root="$2"; shift 2 ;;
    --tracked) tracked=1; shift ;;
    *) paths+=("$1"); shift ;;
  esac
done

root="${root:-$(git rev-parse --show-toplevel)}"

if [ "$tracked" -eq 1 ]; then
  while IFS= read -r p; do
    paths+=("$p")
  done < <(git -C "$root" ls-files)
fi

# Folder names that hold generated output, one per line.
cache_dirs=".terragrunt-cache .terraform __pycache__ .pytest_cache node_modules .cache .venv"

found=()
for p in "${paths[@]:-}"; do
  [ -n "$p" ] || continue
  case "$p" in
    crates/*/tests/golden-corpus/*) continue ;;
  esac
  # A deletion being committed has nothing on disk to check.
  if [ "$tracked" -eq 0 ] && [ ! -e "$root/$p" ]; then
    continue
  fi
  # Walk the folder components and compare each to a cache folder name.
  dir="$(dirname "$p")"
  prefix=""
  IFS='/' read -r -a parts <<< "$dir"
  for part in "${parts[@]}"; do
    prefix="${prefix:+$prefix/}$part"
    for c in $cache_dirs; do
      if [ "$part" = "$c" ]; then
        found+=("$prefix")
        break 2
      fi
    done
  done
done

if [ "${#found[@]}" -eq 0 ]; then
  exit 0
fi

echo "Cache or dependency folders must not be committed:"
printf '%s\n' "${found[@]}" | sort -u | sed 's/^/  /'
echo
echo "Remove them from the index and ignore them, for each folder above:"
echo "  git rm -r --cached <folder>"
echo "  echo '<folder name>/' >> .gitignore"
exit 1
